clone_depth: 1
init:
    - sh: export APPVEYOR_SSH_BLOCK=true
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2019

environment:
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Ht1omER47GnJUbeMEXsJShyZeiJfRIahS3xQwKCg6G9YMae402TYdt8IKYKjPwaUtnI2h0+D1Fa9i/N1WMkf+cO4oMvXP3sS5x3BGDv/OW/3jZrA5qNSQGDYdntOPd9KQGyQ0sH/M4z9VCXlo7QomWgAM8sL9aL3yKlfCNxx0wNw2VnRSBiTu5zQTJ4WmoEWuoMnn8a2Nhgt9QSw+oaLnblWMIrU8hSmY23W45SF0Lh64IslrgD+pUmmrCzR7uL9+nQWr3ApbyZQOSYfQB+HxjuPo9hH2i7mFjWTiZI3oQhXn/0TyazF5ShT3Ee6CAkI2QBflKYaXQ9JBCCtNx3XWwLt7S3l5OSRrS0KZhX+haToAPtCYd2YMi4G/ebA11jH4dSSFiX3+3TfmA/l4Yf+fNWBf0AaiddCs7CnjdRt5vzRAyZ9W9xF8Ldf1nOd7ae9MBtI0jn+nZ2ieFKOZ85j3S9e4y6Yk7sirHxdUib8z5KUsgYWsnuEqDwlLzsyBZk=

    BUILD_NO: $(APPVEYOR_BUILD_NUMBER)
    BRANCH: $(APPVEYOR_REPO_BRANCH)
    REPO: $(APPVEYOR_REPO_NAME)
    matrix:

        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
          PKG_MANAGER_UPDATE_CMD: "sudo apt-get -y update"
          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/install_ubuntu_18_deps.sh /home/appveyor/Qt/5.14.2"
          BUILD_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_ubuntu.sh /home/appveyor/Qt/5.14.2"
          PACKAGE_CMD: ""
          DEPLOY_FILE: ""
          
        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
          PKG_MANAGER_UPDATE_CMD: "sudo apt-get -y update"
          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/install_ubuntu_20_deps.sh /home/appveyor/Qt/5.14.2"
          BUILD_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_ubuntu.sh /home/appveyor/Qt/5.14.2"
          PACKAGE_CMD: ""
          DEPLOY_FILE: ""

#        - ARCH: x86_64
#          ARCH_BIT: 64
#          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_flatpak.sh $BRANCH $REPO"
#          BUILD_CMD: ""
#          PACKAGE_CMD: ""
#          DEPLOY_FILE: "/home/appveyor/projects/scopy/Scopy.flatpak"

install:
    # Install Inno Setup
    - cmd: choco install InnoSetup

build_script:
    # Update MSYS2 - https://www.msys2.org/docs/ci/#appveyor
    - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"  # Core update (in case any core packages are outdated)
    - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"  # Normal update

    # Then run your code
    - cmd: set CHERE_INVOKING='yes'  # Preserve the current working directory
    - cmd: set MSYSTEM='MINGW64'  # Start a 64 bit Mingw environment
    - cmd: C:\msys64\usr\bin\bash -lc "/c/projects/scopy/CI/appveyor/extract_msys_deps.sh"
    - cmd: set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 6"
    - cmd: "%BUILD_DEPS_CMD%"

    - sh: $PKG_MANAGER_UPDATE_CMD
    - sh: echo $BUILD_DEPS_CMD
    - sh: $BUILD_DEPS_CMD

    - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

    - sh: $BUILD_CMD
    - sh: $PACKAGE_CMD

    - echo "### Push artifacts ... "
    - sh: if [[ $DEPLOY_FILE != "" ]]; then appveyor PushArtifact $DEPLOY_FILE; fi

#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
